### ISSUE TITLE
Where's the source code of `@jimpick/hyperdrive-hyperdb-backend`?

### ISSUE THREAD

**Issue by ZhouHansen** [jimpick/dat-shopping-list#62]
dat-shopping-list is really cool! I'm Learning its code. I find `@jimpick/hyperdrive-hyperdb-backend` does not equal to [`mafintosh/hyperdrive`](https://github.com/mafintosh/hyperdrive). e.g. 
```js
const archive = hyperdrive(storage, key, {secretKey})
```
But `mafintosh/hyperdrive`'s doc shows hyperdrive does not accept a `secretKey` in its `opts`.

**Comment by jimpick** [comment]
Sorry, I'm a bit slow to answer. I think it's here:

https://github.com/jimpick/hyperdrive/tree/hyperdb-backend-jim
